[package]
name = "aws-cfn-stack-outputs"
version = "1.0.0"
edition = "2021"

[dependencies]
aws-config = "0.56.1"
aws-sdk-cloudformation = "0.30.0"
convert_case = "0.6.0"
tokio = { version = "1.32.0", features = ["full"] }
